### ISSUE TITLE
Feature Request: Custom exit message (or none)

### ISSUE THREAD

**Issue by dargueta** [SyntaxVoid/py_menu#5]
Hi! Thanks for making this, it looks pretty useful!

I'd like to use this in a tool I'm building at work, but would really rather not leave an unprofessional impression on the 15+ people using it (or God forbid, my boss) when my program exits with "goodbye" and a winking emoji. Could you make this message customizable, e.g. by adding an argument to the `Menu` constructor (and if it's `None` then print nothing)?

Thanks for your time!

**Comment by SyntaxVoid** [comment]
@dargueta I can make that modification and will push an updated version later today!

**Comment by dargueta** [comment]
Awesome, thanks for the quick response!

**Comment by SyntaxVoid** [comment]
The message displayed when you quit is now customizable by optionally passing `on_quit_message="Your custom quit message"` while constructing your toplevel (main) menu. The default quit message is an empty string so no more unprofessional winky faces (unless you add them in yourself :P )
