### ISSUE TITLE
Feature request: Custom/disable automatic "quit program" option

### ISSUE THREAD

**Issue by dargueta** [SyntaxVoid/py_menu#6]
I'd like to have two exit options with my program, "Save and exit" and "Discard changes and exit". Unfortunately it looks like "q. Quit program" option is hard-coded. Could we make this optional?

It'd also be handy to allow a custom message, perhaps by allowing the caller to pass an Option that has `None` for the handler and treating that as an "exit the menu loop" command. This way, I could show menus as needed without actually exiting the program. For example, suppose I have an automated program that needs to occasionally prompt the user if an error occurs, but otherwise doesn't require user interaction and does its own thing.

**Comment by SyntaxVoid** [comment]
Great ideas! You can now disable the built-in `q. Quit Program` option if you wish by passing `show_quit_at_toplevel=False` while constructing your toplevel (main) menu.

In addition, `__call__`-ables that return the string `"break"` will now cause the menu to exit. This can be used to create your alternate exit options. See [https://github.com/SyntaxVoid/py_menu/blob/65a82cb27014aeaca195a2e73d5123f3ee0c08a2/py_menu/examples/custom_exits_example.py](url) for a quick example.
